CREATE DATABASE pubs;
USE pubs;

CREATE TABLE titular(
    DNI_TITULAR VARCHAR(20),
    nombre VARCHAR(50) NOT NULL,
    domicilio VARCHAR(50),
    CONSTRAINT PK_titular PRIMARY KEY (DNI_TITULAR)
);

CREATE TABLE localidad(
    COD_LOCALIDAD INT,
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT PK_localidad PRIMARY KEY (COD_LOCALIDAD)
);

CREATE TABLE pub(
    COD_PUB VARCHAR(20),
    nombre VARCHAR(50) NOT NULL,
    licencia_fiscal VARCHAR(50) NOT NULL,
    domicilio VARCHAR(50),
    fecha_apertura DATE NOT NULL,
    horario VARCHAR(10) NOT NULL,
    DNI_TITULAR VARCHAR(20),
    COD_LOCALIDAD INT,
    CONSTRAINT PK_pub PRIMARY KEY (COD_PUB),
    CONSTRAINT CK_horario CHECK (horario IN ('HOR1','HOR2','HOR3')),
    CONSTRAINT FK_pub_titular FOREIGN KEY (DNI_TITULAR) REFERENCES titular(DNI_TITULAR),
    CONSTRAINT FK_pub_localidad FOREIGN KEY (COD_LOCALIDAD) REFERENCES localidad(COD_LOCALIDAD)
);

CREATE TABLE existencias(
    COD_ARTICULO VARCHAR(20),
    nombre VARCHAR(50) NOT NULL,
    precio INT NOT NULL,
    COD_LOCALIDAD INT,
    CONSTRAINT PK_existencias PRIMARY KEY (COD_ARTICULO),
    CONSTRAINT CK_precio CHECK (precio > 0),
    CONSTRAINT FK_existencias_localidad FOREIGN KEY (COD_LOCALIDAD) REFERENCES localidad(COD_LOCALIDAD)
);

CREATE TABLE empleado(
    DNI_EMPLEADO VARCHAR(20),
    nombre VARCHAR(50) NOT NULL,
    domicilio VARCHAR(50),
    CONSTRAINT PK_empleado PRIMARY KEY (DNI_EMPLEADO)
);

CREATE TABLE pub_empleado(
    COD_PUB VARCHAR(20),
    DNI_EMPLEADO VARCHAR(20),
    funcion VARCHAR(20),
    CONSTRAINT PK_pub_empleado PRIMARY KEY (COD_PUB, DNI_EMPLEADO),
    CONSTRAINT CK_funcion CHECK (funcion IN ('CAMARERO','SEGURIDAD','LIMPIEZA')),
    CONSTRAINT FK_pe_pub FOREIGN KEY (COD_PUB) REFERENCES pub(COD_PUB),
    CONSTRAINT FK_pe_empleado FOREIGN KEY (DNI_EMPLEADO) REFERENCES empleado(DNI_EMPLEADO)
);
