USE centro_educativo;

ALTER TABLE ALUMNOS ADD Edad INT;
ALTER TABLE ALUMNOS ADD CONSTRAINT CK_edad CHECK (Edad BETWEEN 14 AND 65);

ALTER TABLE CURSOS ADD CONSTRAINT CK_horas CHECK (numHoTo IN (30,40,60));
ALTER TABLE CURSOS ADD CONSTRAINT CK_maxAlu CHECK (maxAlu >= 15);

ALTER TABLE ALUMNOS DROP CONSTRAINT alu_sex_CK;

ALTER TABLE PROFESORES DROP COLUMN direPro;

ALTER TABLE CURSOS DROP FOREIGN KEY FK_;

ALTER TABLE PROFESORES DROP PRIMARY KEY;

ALTER TABLE PROFESORES
ADD CONSTRAINT PK_tutores PRIMARY KEY (nombrePro, apellido1Pro, apellido2Pro);

ALTER TABLE PROFESORES
ADD CONSTRAINT UQ_nifPro UNIQUE (nifPro);

RENAME TABLE PROFESORES TO TUTORES;

ALTER TABLE CURSOS
ADD CONSTRAINT FK_cursos_tutores
FOREIGN KEY (nifProfe) REFERENCES TUTORES(nifPro);

DROP TABLE ALUMNOS;


